name: Test Database and Predictions
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Install dependencies
        run: pip install -r app/requirements.txt
        
      - name: Start FastAPI server
        run: pythonw app/main.py

      - name: Run Python tests
        run: python -m unittest -v app/tests/tests.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
