name: Test Database and Predictions
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
        
      - name: Install dependencies
        run: pip install -r app/requirements.txt
        
      - name: Start FastAPI server
        working-directory: app
        run: |
          Start-Process -NoNewWindow -FilePath python -ArgumentList "-m", "uvicorn", "main:app"
          
  test:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Wait for server to start
        run: |
          Start-Sleep -Seconds 5

      - name: Run tests
        run: python -m unittest -v app/tests/tests.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
